grafana:
  env:
    GF_SMTP_PASSWORD: "${GF_SMTP_PASSWORD}"

  envFromSecret: grafana-slack

  grafana.ini:
    smtp:
      enabled: true
      host: smtp.gmail.com:587
      user: upadhaysourav14@gmail.com
      password: $__env{GF_SMTP_PASSWORD}
      from_address: upadhaysourav14@gmail.com
      from_name: Grafana
      startTLS_policy: MandatoryStartTLS

  persistence:
    enabled: true
    type: pvc
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  dashboardsConfigMaps:
    default: grafana-dashboards

  extraConfigmapMounts:
    - name: grafana-alerting
      mountPath: /etc/grafana/provisioning/alerting
      configMap: grafana-alerting
      readOnly: true