replicaCount: 2

image:
  repository: sourabh123421/backend
  tag: "v13"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

container:
  port: 5000

ingress:
  enabled: true
  className: nginx
  host: api.frontend.local
  path: /
  pathType: Prefix

env:
  NODE_ENV: production
  PORT: "5000"
  MONGO_URI: "mongodb://admin:admin123@mongodb:27017/jobmail?authSource=admin"

  EMAIL_USER: "upadhaysourav14@gmail.com"
  EMAIL_PASS: "vickqgdgzlbopqwv"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
