apiVersion: 1

contactPoints:
  - orgId: 1
    name: slack
    receivers:
      - uid: slack
        type: slack
        settings:
          url: ${SLACK_WEBHOOK_URL}
          title: |
            {{ template "default.title" . }}
          text: |
            {{ range .Alerts }}
            *Alert:* {{ .Labels.alertname }}
            *Severity:* {{ .Labels.severity }}
            *Status:* {{ .Status }}
            *Summary:* {{ .Annotations.summary }}
            *Description:* {{ .Annotations.description }}
            {{ end }}
        disableResolveMessage: false
