replicaCount: 2

image:
  repository: sourabh123421/frontend
  tag: "v13"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

container:
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true

  className: nginx

  host: frontend.local

  path: /

  pathType: Prefix    
